apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: homework-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80





